[package]
name = "rust_tts"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_tts"
crate-type = ["cdylib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tts = "0.25.6"
